function [fitresult, gof] = biexpfitc(corrxax, meancorr)
%CREATEFIT(CORRXAX,MEANCORR)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: corrxax
%      Y Output: meancorr
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Jan-2023 04:53:18


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( corrxax, meancorr );
assignin("base","fitxData",xData)
assignin("base","fityData",yData)
% Set up fittype and options.
ft = fittype( 'a*exp(-x/t1)+b*exp(-x/t2)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.Robust = 'Bisquare';


% Fit model to data.
try
    opts.StartPoint = [1 0.1 0 10 10];
    [fitresult, gof] = fit( xData, yData, ft, opts );
catch
    try
        opts.StartPoint = [0.5269 0.5396 -0.064 12.37 1.027];
        [fitresult, gof] = fit( xData, yData, ft, opts );
    catch
        opts.StartPoint = [0.5269 0.5396 -0.064 12.37 1.027]; %insert other values to try fit with
        [fitresult, gof] = fit( xData, yData, ft, opts );
    end
end

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'meancorr vs. corrxax', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'corrxax', 'Interpreter', 'none' );
% ylabel( 'meancorr', 'Interpreter', 'none' );
% grid on


